events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/usuarios/ {
            proxy_pass http://servicio_1:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/servicio_2/ {
            proxy_pass http://servicio_2:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/servicio_3/ {
            proxy_pass http://servicio_3:3003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/servicio_4/ {
            proxy_pass http://servicio_4:3004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/servicio_5/ {
            proxy_pass http://servicio_5:3005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
